name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull comercisandro/cicd-whatbot:latest

    - name: Delete Old Docker container
      run: |
        if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^cicd-whatbot-container\$"; then
          sudo docker rm -f cicd-whatbot-container
        fi

    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-whatbot-container comercisandro/cicd-whatbot:latest

