name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t comercisandro/cicd-whatbot .

    - name: Push the Docker image
      run: docker push comercisandro/cicd-whatbot

    - name: Setup GitHub token
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: echo "GITHUB_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
